sudo: required

language: generic

services: 
    - docker

before_install:
    - docker build -t sergerodriguezequisoft/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sergerodriguezequisoft/docker-react npm run test
